version: "3.9"

services:
  backend:
    build: .
    container_name: flask_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/my_db"

  database:
    image: postgres:12
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
